### ISSUE TITLE
NT Text Based Setup failed on detecting System Partitions

### ISSUE THREAD

**Issue by WGriffithsBLI** [Wack0/maciNTosh#15] opened 2024-07-16 23:47 UTC
Big thank you to Wack0 for the 0.4 update. That did permit the Text Based setup to continue to load and get through the driver load process. Unfortunately it seems that it has hit a snag where NT4 Setup isn't detecting the System Partition that ARC creates and complains that none are defined or considers them full. I do see the setup briefly query the 1900MB partition for C: before this message shows up, so I think it is picking up the drive. 

During the load process I choose Power Mac G3, load both the Mac IDE and HID drivers, and the OpenFirmware Framebuffer driver, then select no mouse and XT keyboard during the hardware spec page. The hard drive is a 15367 MB Maxtor 51536U3.

This is the error below: 
![IMG_3084](https://github.com/user-attachments/assets/fa5b61ee-cb69-4256-a8c8-014f5df39bfc)

(This happens on both NT4 Workstation and Server) - I've tried repartitioning the drive from 8GB to 1900MB, with no improvement. At the moment the CD-Drive is the Master and the Hard Drive is the slave. I tried swapping them around, ARC did boot from the Hard Drive, but wasn't able to load the floppy RAM disk, booting from CD as slave would cause ARC to freeze on the main menu immediately. 

Incidentally, I had this issue before on XP/Server 2003 on ia64, and it was a bug whereby I had to go into fdisk and blitz out all prior partitions on the drive which would force Windows setup to create the system partition. I don't know if that issue stems from the behavior that NT4 has here, but it is more or less the exact same error. 
Oh and the ARCINST.exe program that setup refers to does not exist for PPC, it only appears under the Alpha and MIPS directories on the CD. 

Thank you ever so much for your help and your efforts on this and sorry to be blitzing you with issues.

**Comment by Wack0** [comment] 2024-07-17 00:04
Duplicate of #12 

(and yes I know there's no PPC arcinst, that's part of the reason why i had to write a custom partitioner, technically it does exist for firepower systems but it's undumped)

**Closed by Wack0** 2024-07-17 00:04 UTC
