### ISSUE TITLE
Setupldr hangs on Lombard

### ISSUE THREAD

**Issue by davidmc-ireland** [Wack0/maciNTosh#23] opened 2024-07-22 00:49 UTC
I'm trying to install NT4 on a Lombard Powerbook. Pretty consistently setupldr gets as far as "Setup is loading files (CD-ROM File System). This appears to load (there is disk activity after the screen update) then setup hangs and nothing further occurs. This is after loading the HAL, 2 storage drivers and video drivers as per the README.

I'm tried with the 0.02, 0.03 and 0.05 releases of the firmware package to the same result.

The OS I'm attempting to install is an NT4 workstation disk, I believe RTM (files are dated 09 Aug 1996).

For a hard disk I have an 8GB compact flash card. I've tried formatting with both full disk and a 2000MB partition.

Has anyone experimenting with this seen this issue? Any advice?

**Comment by Wack0** [comment] 2024-07-22 08:48
Hang on early kernel init.

Duplicate of #17 (same issue on yosemite) which appears to be related to memory / hardware failure of some sort (removing all but one ram stick seemed to resolve it for one person)

**Closed by Wack0** 2024-07-22 08:48 UTC
