### ISSUE TITLE
HAL Crash on Trayloader

### ISSUE THREAD

**Issue by TechandMusic462** [Wack0/maciNTosh#11] opened 2024-07-15 16:52 UTC
I'm currently trying to install NT4 on my Bondi Trayloader with added ADB. I'm currently running nightly 20240715_1729, which gets this far before locking up. Releases prior to the CUDA timing changes got stuck on the NT kernel version printout, so there is progress with the latest two releases. Hopefully this information is useful for debugging purposes:

![PXL_20240715_163400417 MP](https://github.com/user-attachments/assets/6d92c092-635d-40e1-9e9e-378a944de396)

**Comment by TechandMusic462** [comment] 2024-07-15 17:04
It seems not loading the HID driver does get me into the installer:

![PXL_20240715_170345905](https://github.com/user-attachments/assets/e53475ca-3882-4315-8587-1b6033b0cd1c)

**Comment by Wack0** [comment] 2024-07-15 17:23
This is a duplicate of #8 - it's the same underlying issue (Cuda driver in HAL broken on real hardware).

**Closed by Wack0** 2024-07-15 17:23 UTC
