### ISSUE TITLE
NT Installer unable to see valid partition on which to install 

### ISSUE THREAD

**Issue by JonObst** [Wack0/maciNTosh#12] opened 2024-07-15 22:32 UTC
I got to the point where it should have enumerated my mass storage devices and located the partition I created from the ARC firmware menu, but it says it can't find a suitable partition.  

Machine type: B&W G3
Build: nt_arcfw_grackle_fwonly_test20240715_1913 (used for partitioning and execution of setupldr)
Disk: 8 GB IDE
Partition size defined: 1500mb

![IMG_0165](https://github.com/user-attachments/assets/e1d0be9a-6c03-484c-80a3-bc824987ab36)

**Comment by Wack0** [comment] 2024-07-15 23:08
hmm, seems something's up with the HAL reading the ARC environent variables on disk...

is the optical drive the ide device 0 and hard drive the ide device 1? if so could you try swapping them? (you will probably need to repartition after that, due to arc paths changing)

**Comment by Wack0** [comment] 2024-07-15 23:17
Additionally, could you try the checked build? (you can find it on winworld) It shows the detected drives on boot (and if you deliberately choose the wrong video driver like VGA the output will remain on the screen), which should be helpful.

**Comment by JonObst** [comment] 2024-07-16 02:03
Swapped the HD and Optical drives and yea that was it.  Do you want me to put them back and run with dbg/chk NT CD still?

![IMG_0169](https://github.com/user-attachments/assets/e4450172-2269-4ba1-956e-b46a7db00f17)

**Comment by JonObst** [comment] 2024-07-16 04:29
I made a video here of the installation process on the B&W G3: https://youtu.be/rt2VsFz5adI, feel free to link/share if you think that would be useful for others.

Overall awesome project, nice work, 10/10!

Happy to run the dbg/chk version of NT 4 still if that is helpful for you.

**Comment by dosdude1** [comment] 2024-07-16 21:47
This same issue occurs most of the time (but not all the time) on my PowerBook G3 Lombard... Seems to mostly happen when re-partitioning the disk a second time after firmware has already been installed once. I've tried with multiple hard disks, which makes no difference. Hard disk has been detected as disk0 consistently.

**Comment by Wack0** [comment] 2024-07-16 22:42
Does a simple reboot solve this when it occurs?

If not, can you do a raw dump of the ARC environment area of the hard disk (1024 bytes / 2 sectors at offset 0xA8200 / sector 1345)?

**Comment by dosdude1** [comment] 2024-07-16 23:41
Rebooting makes no difference, just does the same every time the system is rebooted and installation is attempted again. Here is the requested dump.

[arc_env.bin.zip](https://github.com/user-attachments/files/16257541/arc_env.bin.zip)

**Comment by Wack0** [comment] 2024-07-16 23:46
that looks correct, could you try the checked build to see what drive letters it assigns on boot?
(again, if you deliberately choose an incorrect video driver like VGA, setup will error and hang with the details still on screen)

**Comment by WGriffithsBLI** [comment] 2024-07-17 01:08
Okay, so gone through all of this. I still seem to have a hard lockup of ARC when having the hard drive set to master and the CD drive set to slave. The freeze happens immediately when the main menu shows up and I cannot select anything with the ADB keyboard. 

The hard lockup only occurs when booting from CD and not from Hard Drive, and when the drive's already been partitioned by ARC. I've tried wiping the drive and reformatting it from ARC when booted from CD after having HD as master. Still same issue once the post partition reboot happens.

I could get around the issue if there is a way I could load the RAM disk when booted from ARC using the hard drive.

**Comment by Wack0** [comment] 2024-07-17 08:55
"I could get around the issue if there is a way I could load the RAM disk when booted from ARC using the hard drive."

There's an option in the firmware setup menu for that now.

About the hard lockup, I've seen something similar happen under emulation if I hold the "c" key down for too long. I've worked around it by releasing the key as soon as I see optical drive activity in the emulator logs, I think others have also plugged in a usb keyboard purely for holding down the "c" key on boot...

**Comment by Wack0** [comment] 2024-07-17 10:03
Here's another test build. I modified the HAL to delegate the arc environment reads/writes to a system worker thread. I don't know if this will fix this specific issue, but on initial testing it appears to make installation more stable (no bugcheck at end of graphical setup or at first boot).

[nt_arcfw_grackle_fwonly_test20240715_1913.zip](https://github.com/user-attachments/files/16263733/nt_arcfw_grackle_fwonly_test20240715_1913.zip)

**Comment by Wack0** [comment] 2024-07-17 10:05
Here's another test build. I modifed the HAL to delegate the ARC environment reads/writes to a system worker thread. I don't know if this will fix this specific issue, but on initial testing it appears to make the installation process more stable (I didn't get a bugcheck at end of setup, nor on first boot afterwards).

[nt_arcfw_grackle_fwonly_test20240717_1107.zip](https://github.com/user-attachments/files/16263760/nt_arcfw_grackle_fwonly_test20240717_1107.zip)

**Comment by WGriffithsBLI** [comment] 2024-07-17 20:03
Yes, you were right about not holding 'C' for too long. That's managed to get me back into setup with the HD as master. Unfortunately, it's still returning the no valid system partitions error even with the HD as master. I've validated that ARC sees the hard drive as disk0, so yes I'm real puzzled. I repartitioned again, just with the 1900MB NT partition and the error still persists. 

I'll give your test build a go and see if that makes a difference.

I did find that running the load RAM disk option returns an error when loaded from hard disk, says "Failed to load ramdisk: Invalid device name". 

Haha, I'm beginning to think my B&W is cursed!

**Comment by WGriffithsBLI** [comment] 2024-07-17 21:25
Issue still happens on the test build sadly.

**Comment by Wack0** [comment] 2024-07-17 22:07
Can you try the checked build as mentioned above?

**Comment by WGriffithsBLI** [comment] 2024-07-17 23:11
So I grabbed Build 1381.chk and we get this after going through the driver configuration part of the text-based setup. I'm using your test build of ARC that you uploaded earlier.
![image](https://github.com/user-attachments/assets/3d6098c9-7071-4df8-ab53-74142f9f85bd)

**Comment by Wack0** [comment] 2024-07-18 17:37
Here's a test build, which should allow NT4 checked build to boot. Lots of long delays that can be made a LOT shorter...

[nt_arcfw_grackle_fwonly_test20240718_1835.zip](https://github.com/user-attachments/files/16286958/nt_arcfw_grackle_fwonly_test20240718_1835.zip)

**Comment by WGriffithsBLI** [comment] 2024-07-18 20:28
Thanks for the test build. I can confirm that the checked build is now able to boot. 
Unfortunately the no system partition error persists. I've never used the checked builds before, so I'm not sure of the best process to get the logging from this.

**Comment by Wack0** [comment] 2024-07-18 20:34
If you choose the wrong video driver, like VGA, an error message will show on the boot screen allowing to get the extra text printed by the checked build.

**Comment by Wack0** [comment] 2024-07-18 20:41
That said, I just had a thought and wonder if it's some sort of incompatibilty with the hard drive. The IDE driver under NT does only use the old CHS addressing, perhaps some newer IDE hard drives can't handle it correctly?

**Comment by WGriffithsBLI** [comment] 2024-07-18 21:28
Okay, I get this when I use the VGA driver - it does spit out an error and refuse to continue. However we can see it initializing the drive letters for the system and main partitions.
![image](https://github.com/user-attachments/assets/4c667a73-1ae8-48da-b3c1-50c1d006fa32)

**Comment by Wack0** [comment] 2024-07-18 21:31
It is picking up the hard disk, then.

There might be some other problem with the on-disk ARC environment variables. Has this drive been freshly partitioned using the ARC firmware?

**Comment by WGriffithsBLI** [comment] 2024-07-18 21:34
It sure has, I repartitioned again with a 1900MB main partition when you provided the last test build.

**Comment by Wack0** [comment] 2024-07-18 21:47
Here's a test build that shows some debug output about reading the ARC environment from disk:

[nt_arcfw_grackle_fwonly_test20240718_2248.zip](https://github.com/user-attachments/files/16289534/nt_arcfw_grackle_fwonly_test20240718_2248.zip)

**Comment by WGriffithsBLI** [comment] 2024-07-18 22:54
Hm, that one returns the bugcheck on the NT4 setup again. Is there somewhere within ARC I can get that debug output or is that still supposed to show on the NT4 kernel screen?

**Comment by Wack0** [comment] 2024-07-18 23:07
Still supposed to show on NT boot. That said, it will show on the free build too, you don't need to use the checked build.

**Comment by WGriffithsBLI** [comment] 2024-07-19 17:52
Okay, got it here:
![image](https://github.com/user-attachments/assets/9b34c221-4215-4ad3-9533-f6c5d759cebc)

**Comment by Wack0** [comment] 2024-07-19 20:37
ok, seems more debug output is required. can you try this build?

[nt_arcfw_grackle_fwonly_test20240719_2139.zip](https://github.com/user-attachments/files/16316896/nt_arcfw_grackle_fwonly_test20240719_2139.zip)

**Comment by WGriffithsBLI** [comment] 2024-07-19 21:22
Alrighty, this is what we get with this build: 
![image](https://github.com/user-attachments/assets/458aec94-a9b8-4b69-af4b-dfa9a8e645c3)

**Comment by Wack0** [comment] 2024-07-19 21:51
Can you repartition with the latest build and try again?

**Comment by WGriffithsBLI** [comment] 2024-07-19 22:16
![image](https://github.com/user-attachments/assets/95bc4a9b-8056-4a42-80fa-aec9108f3bdc)
Okay reformatted, I've got 06 now, but the issue still persists!

**Comment by Wack0** [comment] 2024-07-20 00:13
What size of NT partition did you create?

**Comment by WGriffithsBLI** [comment] 2024-07-20 07:56
I was created at 1900MB

**Comment by Wack0** [comment] 2024-07-20 11:10
Still not sure what's going on here. Can you try a different hard disk?

**Comment by Wack0** [comment] 2024-07-20 17:00
When watching Michael MJD's video I noticed there was some crap file in the ARC system partition root directory, which made me realise I was leaving crap in the FAT sectors too.

This test build should fix the issue, you'll need to repartition the drive.

[nt_arcfw_grackle_fwonly_test20240720_1801.zip](https://github.com/user-attachments/files/16321763/nt_arcfw_grackle_fwonly_test20240720_1801.zip)

**Comment by WGriffithsBLI** [comment] 2024-07-20 19:00
Oh my god, that fixed it! Thank you so much!!

**Comment by Wack0** [comment] 2024-07-20 19:03
In that case, fixed in f3ba0a18b569b8a65698255b291da8f8951249d4 and 16e31b8d68443eda2242c81bf69b723d9043cd91, and v0.05 :)

**Closed by Wack0** 2024-07-20 19:03 UTC
